/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as SpreadsRouteImport } from './routes/spreads'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const SpreadsRoute = SpreadsRouteImport.update({
  id: '/spreads',
  path: '/spreads',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/_authenticated/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cards': typeof CardsRoute
  '/spreads': typeof SpreadsRoute
  '/journal': typeof AuthenticatedJournalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cards': typeof CardsRoute
  '/spreads': typeof SpreadsRoute
  '/journal': typeof AuthenticatedJournalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cards': typeof CardsRoute
  '/spreads': typeof SpreadsRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/cards' | '/spreads' | '/journal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/cards' | '/spreads' | '/journal'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cards'
    | '/spreads'
    | '/_authenticated/journal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CardsRoute: typeof CardsRoute
  SpreadsRoute: typeof SpreadsRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spreads': {
      id: '/spreads'
      path: '/spreads'
      fullPath: '/spreads'
      preLoaderRoute: typeof SpreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CardsRoute: CardsRoute,
  SpreadsRoute: SpreadsRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
